blogproject/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

blogproject/blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
	url(r'^$',views.IndexView.as_view(), name='index'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
	url(r'^archives/(?P<year>[0-9]{1,4})/(?P<month>[0-9]{1,2})/$', views.archivesView.as_view(), name='archives'),
	url(r'^category/(?P<pk>[0-9]+)/$',  views.CategoryView.as_view(), name='category'),
	url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),

]

blogproject/blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from DjangoUeditor import urls as djud_urls
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^ueditor/',include(djud_urls)),
    url(r'^search/', include('haystack.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#仅解决测试环境中(debug=True),解决静态文件404，部署环境，nginx配置会自动访问

    

blogproject/comments/urls.py
from django.conf.urls import url
from . import views

app_name='comments'

urlpatterns = [
	url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

blogproject/blog/models.py
#coding:utf8
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from DjangoUeditor.models import UEditorField
import django.utils.timezone as timezone
class Category(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

class Tag(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

class Post(models.Model):
	title = models.CharField(verbose_name='标题',max_length=70)
	body = UEditorField(u"文章正文",height=300,width=700,default=u'',blank=True,imagePath="uploads/blog/images/",
                           toolbars='besttome',filePath='uploads/blog/files/')
	created_time = models.DateTimeField(u"发布日期",default = timezone.now,editable=True)
	modified_time = models.DateTimeField(u'更新时间',auto_now=True,null=True)
	excerpt = models.CharField(verbose_name='摘要',max_length=200,blank=True)
	category = models.ForeignKey(Category,verbose_name='分类')
	tags = models.ManyToManyField(Tag,verbose_name='标签',blank=True)
	author = models.ForeignKey(User,verbose_name='用户')
	views = models.PositiveIntegerField(default=0)

	def increase_views(self):
		self.views +=1
		self.save(update_fields=['views'])
	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:detail',kwargs={'pk':self.pk})

	class Meta:
		ordering = ['-created_time']

blogproject/comments/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
	STATUS_CHOICES =(
			('newsubmit','NewSubmit'),
			('pass','Pass'),
		)
	name = models.CharField(max_length=100)
	email = models.EmailField(max_length=255)
	url = models.URLField(blank=True)
	text = models.TextField()
	created_time = models.DateTimeField(auto_now_add=True)
	status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='newsubmit')
	post = models.ForeignKey('blog.Post')

	def __str__(self):
		return self.text[:20]

blogproject/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Category
from comments.forms import CommentForm
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

class IndexView(ListView):
	model = Post
	template_name = 'blog/index.html'
	context_object_name = 'post_list'
	paginate_by = 5
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		paginator = context.get('paginator')
		page = context.get('page_obj')
		is_paginated = context.get('is_paginated')
		pagination_data = self.pagination_data(paginator, page, is_paginated)
		context.update(pagination_data)
		return context

	def pagination_data(self, paginator, page, is_paginated):
		if not is_paginated:
			return {}
		left = []
		right = []
		left_has_more = False
		right_has_more = False
		first = False
		last = False
		page_number = page.number
		total_pages = paginator.num_pages
		page_range = paginator.page_range

		if page_number == 1:
			right = page_range[page_number:page_number + 2]
			if right[-1] < total_pages - 1:
				right_has_more = True
			if right[-1] < total_pages:
				last = True

		elif page_number == total_pages:
			left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
			if left[0] > 2:
				left_has_more = True
			if left[0] > 1:
				first = True
		else:
			left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
			right = page_range[page_number:page_number + 2]
			if right[-1] < total_pages - 1:
				right_has_more = True
			if right[-1] < total_pages:
				last = True
			if left[0] > 2:
				left_has_more = True
			if left[0] > 1:
				first = True

		data = {
			'left': left,
			'right': right,
			'left_has_more': left_has_more,
			'right_has_more': right_has_more,
			'first': first,
			'last': last,
		}

		return data
class PostDetailView(DetailView):
	model = Post
	template_name = 'blog/detail.html'
	context_object_name = 'post'

	def get(self, request, *args,**kwargs):
		response = super(PostDetailView, self).get(request,*args, **kwargs)
		self.object.increase_views()
		return response

	def get_object(self, queryset=None):
		post = super(PostDetailView, self).get_object(queryset=None)
		return post

	def get_context_data(self, **kwargs):
		context = super(PostDetailView, self).get_context_data(**kwargs)
		form = CommentForm()
		comment_list = self.object.comment_set.all().filter(status='pass')
		context.update({
			'form':form,
			'comment_list':comment_list
			})
		return context

class archivesView(ListView):
	model = Post
	template_name = 'blog/index.html'
	context_object_name = 'post_list'

	def get_queryset(self):
		year = self.kwargs.get('year')
		month = self.kwargs.get('month')
		return super(archivesView, self).get_queryset().filter(created_time__year=year,
									created_time__month=month)

class CategoryView(ListView):
	model = Post
	template_name = 'blog/index.html'
	context_object_name = 'post_list'

	def get_queryset(self):
		cate = get_object_or_404(Category , pk = self.kwargs.get('pk'))
		return super(CategoryView, self).get_queryset().filter(category=cate)

class TagView(ListView):
	model = Post
	template_name = 'blog/index.html'
	context_object_name = 'post_list'


	def get_qeryset(self):
		tag = get_object_or_404(Tag,pk=self.kwargs.get('pk'))
		return super(TagView, self).get_queryset().filter(tags=tag)

blogproject/templates/blog/detail.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block main %}
<article class="post post-{{ post.pk }}">
  <header class="entry-header">
    <h1 class="entry-title">{{ post.title }}</h1>
    <div class="entry-meta">
      <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
      <span class="post-date"><a href="#"><time class="entry-date"
                                                datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
      <span class="post-author"><a href="#">{{ post.author }}</a></span>
      <span class="comments-link"><a href="#">评论 {{ post.comment_set.count }}</a></span>
      <span class="views-count"><a href="#">阅读 {{ post.views }}</a></span>
    </div>
  </header>
  <div class="entry-content clearfix">
    {{ post.body|safe }}
     <div class="widget-tag-cloud">
                <ul>
                    标签：
                    {% for tag in post.tags.all %}
                        <li><a href="{% url 'blog:tag' tag.pk %}"># {{ tag.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
  </div>
</article>
<form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-4">
      <label for="{{ form.name.id_for_label }}">名字：</label>
      {{ form.name }}
      {{ form.name.errors }}
    </div>
    <div class="col-md-4">
      <label for="{{ form.email.id_for_label }}">邮箱：</label>
      {{ form.email }}
      {{ form.email.errors }}
    </div>
    <div class="col-md-4">
      <label for="{{ form.url.id_for_label }}">URL：(可不填)</label>
      {{ form.url }}
      {{ form.url.errors }}
    </div>
    <div class="col-md-12">
      <label for="{{ form.text.id_for_label }}">评论：</label>
      {{ form.text }}
      {{ form.text.errors }}
      <button type="submit" class="comment-btn">提交</button>
    </div>
  </div>    <!-- row -->
</form>
<ul class="comment-list list-unstyled">
  {% for comment in comment_list %}
  <li class="comment-item">
    <span class="nickname">{{ comment.name }}</span>
    <time class="submit-date">{{ comment.created_time }}</time>
    <div class="text">
      {{ comment.text|markdown }}
    </div>
  </li>
  {% empty %}
  暂无评论
  {% endfor %}
</ul>
{% endblock main %}
{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        <ul>
            <li>
                <a href="#">教程特点</a>
            </li>
            <li>
                <a href="#">谁适合这个教程</a>
            </li>
            <li>
                <a href="#">在线预览</a>
            </li>
            <li>
                <a href="#">资源列表</a>
            </li>
            <li>
                <a href="#">获取帮助</a>
            </li>
        </ul>
    </div>
{% endblock toc %}

blogproject/templates/blog/index.html
{%extends 'base.html' %}
{% load blog_tags %}
{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time}}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">评论 {{ post.comment_set.count }} </a></span>
                            <span class="views-count"><a href="#"> 阅读 {{ post.views }} </a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ post.body|safe|truncatechars_html:52 }}</p>
                        <div class="read-more cl-effect-14">
                            <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
    {% empty %}
        <div class='mo-post'>暂时还没有发布文章！</div>
    {% endfor %}
{% if is_paginated %}
    <div class="pagination">
      {% if first %}
        <a href="?page=1">1</a>
      {% endif %}
      {% if left %}
        {% if left_has_more %}
            <span>...</span>
        {% endif %}
        {% for i in left %}
            <a href="?page={{ i }}">{{ i }}</a>
        {% endfor %}
      {% endif %}
      <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
      {% if right %}
        {% for i in right %}
            <a href="?page={{ i }}">{{ i }}</a>
        {% endfor %}
        {% if right_has_more %}
            <span>...</span>
        {% endif %}
      {% endif %}
      {% if last %}
        <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
      {% endif %}
    </div>
{% endif %}
{% endblock main %}